"""followers

Revision ID: 201a08b62eb9
Revises: 27330fd8bc9d
Create Date: 2019-10-13 15:50:12.810311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201a08b62eb9'
down_revision = '27330fd8bc9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
