"""added about_me and last_seen fields

Revision ID: 27330fd8bc9d
Revises: 67c0499631d1
Create Date: 2019-10-11 15:16:32.787782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27330fd8bc9d'
down_revision = '67c0499631d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
